#pragma once
#define PLATFORM_BIT  1
#define PLAYER_BIT  2
#define FOOT_BIT  4
#define BULLET_BIT  8
#define SKREE_BIT  16
#define BOMBITEM_BIT 32
#define ZOOMER_BIT  64
#define MARUMARIITEM_BIT 128
#define HEALTHITEM_BIT 256
#define HEAD_BIT 512
#define EXPLOSION_BIT 1024
#define BREAKABLEPLATFORM_BIT 2048

